services:
  watcher:
    build:
      context: .
      dockerfile: Dockerfile.watcher
    command: npm run watcher
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - prisma-db:/usr/src/app/prisma

  minter:
    build:
      context: .
      dockerfile: Dockerfile.minter
    command: npm run minter
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - prisma-db:/usr/src/app/prisma

volumes:
  prisma-db:
