name: Deploy to Droplet

on:
  push:
    branches:
      - master # Adjust to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd ~/Projects/blockchain-migration-tool-backend
            git pull
            docker compose build
            docker compose up -d
